on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acr4kubernetes.azurecr.io
        username: ${{ secrets.acr_acr4kubernetes_username }}
        password: ${{ secrets.acr_acr4kubernetes_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acr4kubernetes.azurecr.io/demoakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acr4kubernetes.azurecr.io/demoakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_demoakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demoaksclusterb44a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demoaksclusterb44a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demoaksclusterb44a
        container-registry-url: acr4kubernetes.azurecr.io
        container-registry-username: ${{ secrets.acr_acr4kubernetes_username }}
        container-registry-password: ${{ secrets.acr_acr4kubernetes_password }}
        secret-name: demoaksclustdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demoaksclusterb44a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acr4kubernetes.azurecr.io/demoakscluster:${{ github.sha }}
        imagepullsecrets: |
          demoaksclustdockerauth
